#!/bin/bash

set -eu

mailroot=/srv/mail/domains

chown root:root "$mailroot"
chmod 700 "$mailroot"
setfacl -b \
	-m u:Debian-exim:rx \
	-m u:dovecot:x \
	-m u:rrmail:x \
	"$mailroot"

find "$mailroot" -mindepth 1 -maxdepth 1 -type d | while read domain; do
	chown root:root "$domain"
	chmod 700 "$domain"
	setfacl -b \
		-m u:Debian-exim:x \
		-m u:dovecot:x \
		-m u:rrmail:x \
		"$domain"

	if test -f "$domain/redirect"; then
		chown root:Debian-exim "$domain/redirect"
		chmod 640 "$domain/redirect";
	fi

	if test -f "$domain/passwd.in"; then
		chown root:root "$domain/passwd.in"
		chmod 600 "$domain/passwd.in"

		chown root:root "$domain/passwd"
		chmod 600 "$domain/passwd"
		setfacl -b \
			-m u:Debian-exim:r \
			-m u:dovecot:r \
			"$domain/passwd"
	fi

	if test -f "$domain/aliases"; then
		chown root:Debian-exim "$domain/aliases"
		chmod 640 "$domain/aliases"
	fi

	if test -d "$domain/users"; then
		chown root:rrmail "$domain/users"
		chmod 770 "$domain/users"

		find "$domain/users" -mindepth 1 -maxdepth 1 -type d | while read user; do
			chown -R rrmail:rrmail "$user"
			find "$user" -type d -exec chmod 700 {} +
			find "$user" -type f -exec chmod 600 {} +
		done
	fi
done

# vim: ts=4 sts=4 sw=4 noet
